## Products.
---
- name: Job Management & Tracking System (JMTS)
  categories: Order Management
  description: JMTS is an Enterprise Resource Planning (ERP) software that 
               can be used by organizations to manage day-to-day business 
               activities such as costing, human resource management, 
               job management and reporting.
  link: /jmts 
  image:
- name: Client Management (CM)
  categories: Customer Relationship Management
  description: CM is a Customer Relationship Management (CRM) system that manages 
               your customer interactions, streamlines sales, and enhances 
               relationships by centralizing customer data, facilitating 
               communication, and optimizing business processes for improved 
               customer satisfaction and retention.
  link: /cm
  image: 