## Products.
---
- name: Job Management & Tracking System (JMTS)
  categories: Order Management
  description: JMTS is an Enterprise Resource Planning (ERP) software that 
               can be used by organizations to manage day-to-day business 
               activities such as costing, human resource management, 
               job management and reporting.
  link: /jmts 
  image:
- name: Client Management (CM)
  categories: Customer Relationship Management
  description: CM is a Customer Relationship Management (CRM) system that manages 
               your customer interactions, streamlines sales, and enhances 
               relationships by centralizing customer data, facilitating 
               communication, and optimizing business processes for improved 
               customer satisfaction and retention.
  link: /cm
  image:
- name: Gnucash 2.4 Small Business Accounting - Beginner's Guide
  categories: Accounting Book
  description: This book is a comprehensive beginner's guide that teaches you to 
               use GnuCash from scratch with jargon-free step-by-step tutorials 
               packed with tips.There are multiple choice questions to make 
               learning more interesting and additional challenges thrown at 
               the more adventurous user for a deep grasp of the topic.
  link: https://amzn.to/48Qwy6x
  image: https://m.media-amazon.com/images/I/71PUXlqDR2L._SL1360_.jpg