## Services.
---
- title: Metrology &amp; Testing Consultancy
  icon: bi bi-rulers
  description: We offer consultancy and contract services in energy and AC/DC metrology and testing.
  link: /metrology-and-testing 
- title: Product Development
  icon: bi bi-bicycle
  description: We offer services in the research and development of electronic and mechanical products.
  link: /product-development   
- title: Web Application Development
  icon: bi bi-globe
  description: We develop web applications for intranet and client facing purposes.
  link: /web-application-development 
- title: Mobile Application Development
  icon: bi bi-phone
  description: We develop cross-platform mobile apps for business and scientific purposes.
  link: /mobile-application-development